# Generated by Django 4.2.1 on 2023-08-17 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EurUsd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DecimalField(decimal_places=7, max_digits=10)),
                ('open', models.DecimalField(decimal_places=7, max_digits=10)),
                ('close', models.DecimalField(decimal_places=7, max_digits=10)),
                ('high', models.DecimalField(decimal_places=7, max_digits=10)),
                ('low', models.DecimalField(decimal_places=7, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=7, max_digits=10)),
                ('date', models.DateTimeField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
            ],
        ),
    ]
