# Generated by Django 4.2.1 on 2023-08-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appreact', '0003_alter_eurusd_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eurusd',
            name='close',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eurusd',
            name='high',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eurusd',
            name='low',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eurusd',
            name='open',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='eurusd',
            name='timestamp',
            field=models.FloatField(verbose_name=2),
        ),
        migrations.AlterField(
            model_name='eurusd',
            name='volume',
            field=models.FloatField(),
        ),
    ]
